FROM ubuntu:18.04
# 
# build linux-2.6.39
# with gcc-4.8 × 报错 Can't use 'defined(@array)' (Maybe you should just omit the defined()?) at kernel/timeconst.pl line 373.
# 		因为 perl 版本较新，有 BUG
# with gcc-5 × 报错 kernel/bounds.c:1:0: error: code model kernel does not support PIC mode
#
# build linux-3.19
# with gcc-4.8 ✓
# with gcc-5 ✓
# with gcc-6 × 开始报错： include/linux/compiler-gcc.h:106:30: fatal error: linux/compiler-gcc6.h: No such file or directory

# ubuntu:18.04 默认 gcc-7.5
RUN	apt-get update \
	&& apt-get -y install libncurses5-dev gdb qemu make dos2unix bc gcc-5\
	&& DEBIAN_FRONTEND=noninteractive apt-get -y install build-essential \
	&& apt-get clean -y && rm -rf /var/lib/apt/lists/*

RUN update-alternatives --install  /usr/bin/gcc gcc /usr/bin/gcc-5 2022

RUN mkdir /code

WORKDIR /code

