FROM ubuntu:22.04
# build 5.

# ubuntu:22.04 默认 gcc-11.3.0
# ubuntu:22.04 后， 需要安装 qemu-kvm 而非 qemu ，安装后，依然可以使用 qemu-system-aarch64
RUN	apt-get update \
	&& DEBIAN_FRONTEND=noninteractive apt-get -y install build-essential \
	&& apt-get -y install libncurses5-dev gdb make dos2unix bc \
	&& apt-get -y install flex bison libssl-dev \
	&& apt-get -y install qemu-kvm \
	&& apt-get clean -y && rm -rf /var/lib/apt/lists/*

# RUN update-alternatives --install  /usr/bin/gcc gcc /usr/bin/gcc-5 2022

RUN mkdir /code

WORKDIR /code

