FROM ubuntu:22.04
# build 5.

# ubuntu:22.04 默认 gcc-11.3.0
RUN	apt-get update \
	&& apt-get -y install libncurses5-dev gdb qemu make dos2unix bc \
	&& apt-get -y install flex bison libssl-dev \
	&& DEBIAN_FRONTEND=noninteractive apt-get -y install build-essential \
	&& apt-get clean -y && rm -rf /var/lib/apt/lists/*

# RUN update-alternatives --install  /usr/bin/gcc gcc /usr/bin/gcc-5 2022

RUN mkdir /code

WORKDIR /code

